### ISSUE TITLE
IOError: could not get source code when running in interpreter

### ISSUE THREAD

**Issue by inasring** [google/tangent#10]
I opened the interpreter with "python" (no flags) and pasted the following:

```
import tangent as t
def f(x):
    return x*x

t.grad(f)

```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tangent/grad_util.py", line 178, in grad
    node, namespace = grad_tree(func, wrt, motion, mode, preserve_result, verbose)
  File "/usr/local/lib/python2.7/dist-packages/tangent/grad_util.py", line 99, in grad_tree
    node, required = grad_ast(func, wrt, motion, mode, preserve_result, verbose)
  File "/usr/local/lib/python2.7/dist-packages/tangent/grad_util.py", line 47, in grad_ast
    node = annotate.resolve_calls(func)
  File "/usr/local/lib/python2.7/dist-packages/tangent/annotate.py", line 105, in resolve_calls
    node = quoting.parse_function(func)
  File "/usr/local/lib/python2.7/dist-packages/tangent/quoting.py", line 83, in parse_function
    return parse_string(inspect.getsource(fn))
  File "/usr/lib/python2.7/inspect.py", line 701, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/lib/python2.7/inspect.py", line 690, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python2.7/inspect.py", line 538, in findsource
    raise IOError('could not get source code')
IOError: could not get source code

```

Pasting to IPython interpreter works
Running from a file works (python script.py)
Running from an interpreter after a file runs works (python -i script.py)

Installed through pip  
python 2.7.12
ubuntu 16.04

**Comment by alexbw** [comment]
We can't get around this issue (Tangent can't differentiate without the source code, and you'll note the error is in the standard library `inspect` module), but we can throw a better error message. Thanks for reporting this.
