### ISSUE TITLE
Unpackings not supported

### ISSUE THREAD

**Issue by stefdoerr** [google/tangent#19]
Does `np.shape` not work? I don't understand exactly the error. Or you cannot dynamically create an array from the shape of another array?

```python
def featurize3(wrapped):
    feats = np.zeros((4, np.shape(wrapped)[0]))
    return feats

grad = tangent.grad(featurize3)
```

```pytb
Traceback (most recent call last):

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-27-0194034bf20a>", line 1, in <module>
    grad = tangent.grad(featurize3, preserve_result=True)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/grad_util.py", line 178, in grad
    node, namespace = grad_tree(func, wrt, motion, mode, preserve_result, verbose)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/grad_util.py", line 111, in grad_tree
    mode, True, verbose)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/grad_util.py", line 48, in grad_ast
    fence.validate(node, inspect.getsource(func))

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 34, in validate
    lf.visit(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 95, in visit_Module
    self._allow_and_continue(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 87, in _allow_and_continue
    self.generic_visit(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 364, in visit_FunctionDef
    self._allow_and_continue(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 87, in _allow_and_continue
    self.generic_visit(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 377, in visit_Return
    self._allow_and_continue(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 87, in _allow_and_continue
    self.generic_visit(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/ast.py", line 263, in generic_visit
    self.visit(value)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 250, in visit_Call
    self._allow_and_continue(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 87, in _allow_and_continue
    self.generic_visit(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/ast.py", line 261, in generic_visit
    self.visit(item)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/ast.py", line 253, in visit
    return visitor(node)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 144, in visit_Starred
    self._reject(node, 'Unpackings are not supported')

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 91, in _reject
    self._raise_error(msg)

  File "/shared/sdoerr/Software/miniconda3/lib/python3.6/site-packages/tangent/fence.py", line 74, in _raise_error
    raise TangentParseError(msg, ('<stdin>', lineno, offset + 1, line))

  File "<stdin>", line 4
    return f_raw(*argvals, **kwargs)
             ^
TangentParseError: Unpackings are not supported
```

**Comment by stefdoerr** [comment]
Oh dammit sorry my mistake. Closing issue!
