### ISSUE TITLE
python3: pip install fails with UnicodeDecodeError

### ISSUE THREAD

**Issue by utke1** [google/tangent#50]
this seems to be related to issue #13 but I tried it Dec/1 and got the following error:
```
Collecting tangent
  Downloading tangent-0.1.8.tar.gz (81kB)
    100% |################################| 81kB 1.9MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-bifyt5f0/tangent/setup.py", line 5, in <module>
        readme = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 498: ordinal not in range(128)
```
Note this was  an attempt to install under python 3.5.2 (standard ubuntu 16 package). 
In contrast it seems like the python2.7 install does work OK.

**Comment by alexbw** [comment]
Yep, more non-ASCII characters slipped into the README. I removed them in
120b210
<https://github.com/google/tangent/commit/120b2107a75d4c806815067abe98a77535e2488c>,
and will cut a new release on pip soon.

**Comment by alexbw** [comment]
Release v0.1.9 has been tagged and should be available on PyPI in an hour or so. Please let me know if that fixes the issue when you get a chance.

**Comment by utke1** [comment]
As of today (Dec/11) it looks like the 0.1.9 version hasn't shown up in PyPI: 
```
~> pip3 --no-cache-dir install -v tangent==0.1.9
Collecting tangent==0.1.9
  1 location(s) to search for versions of tangent:
  * https://pypi.python.org/simple/tangent/
  Getting page https://pypi.python.org/simple/tangent/
  Starting new HTTPS connection (1): pypi.python.org
  "GET /simple/tangent/ HTTP/1.1" 200 304
  Analyzing links from page https://pypi.python.org/simple/tangent/
    Found link https://pypi.python.org/packages/91/8f/a25e275dc0cf948bbe6b15a759b31e7f02ed51e7cfb759e4e9a8a74775d6/tangent-0.1.8.tar.gz#md5=ec87e7257211a187f4b99c7ca3e6ac83 (from https://pypi.python.org/simple/tangent/), version: 0.1.8
    Found link https://pypi.python.org/packages/c8/21/7a0b6cd0b3588959f3850aafef053e1e6db32037e609adb89f02b24d5e12/tangent-0.1.7.tar.gz#md5=f429f52ca72aec0b2c086dc4d4db27ad (from https://pypi.python.org/simple/tangent/), version: 0.1.7
  Could not find a version that satisfies the requirement tangent==0.1.9 (from versions: 0.1.7, 0.1.8)
Cleaning up...
No matching distribution found for tangent==0.1.9
Exception information:
Traceback (most recent call last):
  File "/home/jutke/.local/lib/python3.5/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/jutke/.local/lib/python3.5/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/home/jutke/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/jutke/.local/lib/python3.5/site-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/home/jutke/.local/lib/python3.5/site-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/jutke/.local/lib/python3.5/site-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for tangent==0.1.9
```

**Comment by utke1** [comment]
works for me now - thanks!

**Comment by alexbw** [comment]
Awesome.
