### ISSUE TITLE
Error when importing Tangent - Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by ppau1** [google/tangent#61]
### Problem 

I get the following error when running `import tangent` in Python 3.6:

```python
In [1]: import tangent
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     57
---> 58   from tensorflow.python.pywrap_tensorflow_internal import *
     59   from tensorflow.python.pywrap_tensorflow_internal import __version__

~/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow_internal = swig_import_helper()
     29     del swig_import_helper

~/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
     25             finally:

~/.conda/envs/py36/lib/python3.6/imp.py in load_module(name, file, filename, details)
    242         else:
--> 243             return load_dynamic(name, filename, file)
    244     elif type_ == PKG_DIRECTORY:

~/.conda/envs/py36/lib/python3.6/imp.py in load_dynamic(name, path, file)
    342             name=name, loader=loader, origin=path)
--> 343         return _load(spec)
    344

ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found (required by /home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
<ipython-input-1-b7bc666cce03> in <module>()
----> 1 import tangent

~/.conda/envs/py36/lib/python3.6/site-packages/tangent/__init__.py in <module>()
     18 import gast
     19
---> 20 from tangent import annotate
     21 from tangent import ast as ast_
     22 from tangent import compile as compile_

~/.conda/envs/py36/lib/python3.6/site-packages/tangent/annotate.py in <module>()
     27 from tangent import cfg
     28 from tangent import quoting
---> 29 from tangent import tracing
     30 from tangent import utils
     31

~/.conda/envs/py36/lib/python3.6/site-packages/tangent/tracing.py in <module>()
     14 """Utilities for tracing code, a useful fallback when ahead-of-time AD fails.
     15 """
---> 16 from tensorflow.python.eager.backprop import make_vjp
     17
     18

~/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/__init__.py in <module>()
     22
     23 # pylint: disable=wildcard-import
---> 24 from tensorflow.python import *  # pylint: disable=redefined-builtin
     25 # pylint: enable=wildcard-import
     26

~/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/__init__.py in <module>()
     47 import numpy as np
     48
---> 49 from tensorflow.python import pywrap_tensorflow
     50
     51 # Protocol buffers

~/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     72 for some common reasons and solutions.  Include the entire stack trace
     73 above this error message when asking for help.""" % traceback.format_exc()
---> 74   raise ImportError(msg)
     75
     76 # pylint: enable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

ImportError: Traceback (most recent call last):
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.7' not found (required by /home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

### System information:
```
Red Hat Enterprise Linux Server release 5.3 (Tikanga)
Amazon Linux Bare Metal release 2012.03
```

**Comment by stefdoerr** [comment]
Did you try `pip install tensorflow-gpu`? It fixed it for me

**Comment by ppau1** [comment]
@stefdoerr, I just installed `tensorflow-gpu`. I now get a slightly different error:

```python
▶ python -c 'import tangent'
Traceback (most recent call last):
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tangent/__init__.py", line 20, in <module>
    from tangent import annotate
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tangent/annotate.py", line 29, in <module>
    from tangent import tracing
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tangent/tracing.py", line 16, in <module>
    from tensorflow.python.eager.backprop import make_vjp
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/pauperei/.conda/envs/py36/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /home/pauperei/.conda/envs/py36/lib/python3.6/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
````

**Comment by mdanatg** [comment]
I found this issue on the TensorFlow repo that seems to match the error you're seeing: https://github.com/tensorflow/tensorflow/issues/53

It appears that TensorFlow requires glibc > 2.17. You could try to find yours by running `ldd --version`. This [SO post](https://askubuntu.com/questions/736208/upgrading-glibc) might help with the upgrade steps.

**Comment by ppau1** [comment]
>It appears that TensorFlow requires glibc > 2.17.

I think you're right. I'm running glibc 2.12. 
That's unfortunate. I'm not really using TensorFlow and I was planning to use tangent to calculate gradients of Numpy functions. Is there a way to avoid the TensorFlow dependency?

**Comment by mdanatg** [comment]
There is an unsupported way, though it might be a bit impractical. It requires installing Tangent from sources, see below:

1. Clone this repo: `git clone https://github.com/google/tangent.git`
2. Edit `tangent/__init__.py` and remove the line `from tangent.tf_extensions import *`
3. Edit `tangent/tracing.py` and remove the line `from tensorflow.python.eager.backprop import make_vjp`
4. Remove the "tf-nightly" line from `setup.py`
5. Reinstall the pip package `cd tangent`, `pip install -e .`

That will disable all TF-related functionality, but if your code only uses NumPy everything else should still work.

**Comment by ppau1** [comment]
That worked.

Thanks!
