### ISSUE TITLE
ValueError: Cannot differentiate function

### ISSUE THREAD

**Issue by wangkuiyi** [google/tangent#75]
```
>>> def f(x):
...     out = x * x
...     return out
... 
>>> import tangent
>>> df = tangent.grad(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tangent/grad_util.py", line 386, in grad
    verbose=verbose)
  File "/usr/local/lib/python2.7/dist-packages/tangent/grad_util.py", line 290, in autodiff
    check_dims, verbose)
  File "/usr/local/lib/python2.7/dist-packages/tangent/grad_util.py", line 144, in autodiff_tree
    check_dims, verbose)
  File "/usr/local/lib/python2.7/dist-packages/tangent/grad_util.py", line 89, in autodiff_ast
    node = annotate.resolve_calls(func)
  File "/usr/local/lib/python2.7/dist-packages/tangent/annotate.py", line 109, in resolve_calls
    node = quoting.parse_function(func)
  File "/usr/local/lib/python2.7/dist-packages/tangent/quoting.py", line 90, in parse_function
    'have accessible source code.' % e)
ValueError: Cannot differentiate function: could not get source code. Tangent must be able to access the source code of the function. Functions defined in a Python interpreter and functions backed by C extension modules do not have accessible source code.
```

I am running Python and tangent in a Docker container, where the image is defined by this [Dockerfile](https://gist.github.com/wangkuiyi/2c6e187e6909b9c5df3482ef28f00489).

**Comment by alexbw** [comment]
Hi, it looks like you're working it the default Python console, which
doesn't provide source code for functions defined inline. Try running this
code in a script or the IPython console, or a notebook.

**Comment by wangkuiyi** [comment]
Oh, yes! Thanks @alexbw !
