### ISSUE TITLE
AttributeError: module 'builtins' has no attribute 't'

### ISSUE THREAD

**Issue by amirziai** [google/tangent#8]
Getting `AttributeError: module 'builtins' has no attribute 't'` when running the Hessian-vector products example:
```
def f(x):
    a = x * x * x
    b = a * x ** 2.0
    return tf.reduce_sum(b)

hvp = tangent.grad(tangent.grad(f, mode='reverse'), mode='forward')
```

**Comment by alexbw** [comment]
What OS and Python version are you running?

**Comment by amirziai** [comment]
Mac `macOS Sierra 10.12.6` and `Python 3.5.4`

**Comment by mdanatg** [comment]
Just uploaded a new pip package (0.1.4) - could you try again?

**Comment by amirziai** [comment]
```
➜  ~ pip install tangent
Collecting tangent
  Using cached tangent-0.1.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/8n/xtn3n2c50tbgtcr2pnh21dl4002rn2/T/pip-build-jonxif42/tangent/setup.py", line 7, in <module>
        with open('LICENSE') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/8n/xtn3n2c50tbgtcr2pnh21dl4002rn2/T/pip-build-jonxif42/tangent/
```

**Comment by mdanatg** [comment]
Oops, sorry about that. how about now?

**Comment by amirziai** [comment]
Issue is resolved now. Thanks @mdanatg and @alexbw
